module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Projects',
      collapsed: false,
      items: [
        // This 'autogenerated' ID tells Docusaurus to look at the folder structure
        {
          type: 'autogenerated',
          dirName: 'projects', 
        },
      ],
    },
  ],
};